import { type NextPage } from "next";
import Head from "next/head";
import Card from "~/components/Cards/Card";
import Navbar from "~/components/Navbar";
import GlassCard from "~/components/Cards/GlassCard";
import Footer from "~/components/Footer";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Blogging App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col bg-primary-900 bg-opacity-50 px-5">
        <Navbar />
        <div className="mt-3 grid grid-cols-1 gap-2 md:grid-cols-3">
          <GlassCard />
          <GlassCard />
          <GlassCard />
        </div>
        <div className="mt-5 flex flex-col gap-4">
          <Card reverse={false} />
          <Card reverse={true} />
        </div>
        {/* <div className="absolute top-0 left-0 z-30 flex h-screen w-screen items-center justify-center bg-opacity-25 backdrop-blur-md">
          <div className="h-[600px] w-[500px] rounded-md bg-primary-900  shadow-xl"></div>
        </div> */}

        {/* <div className="absolute top-0 left-0 z-30 flex h-screen w-screen items-center justify-center ">
          <div className="h-[600px] w-[500px] rounded-md bg-primary-900 bg-opacity-70 shadow-xl backdrop-blur-md"></div>
        </div> */}
        <Footer />
      </main>
    </>
  );
};

export default Home;
